import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import NavBar from "@/components/NavBar"
import { ClerkProvider } from "@clerk/nextjs"
import Providers from "@/components/Providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      {/*publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}*/}
      <html lang="fr" className="h-full">
        <body
          className={cn(
            "relative h-full font-sans antialiased",
            inter.className
          )}>
          <main className="relative flex flex-col min-h-screen">
            <Providers>
              <NavBar />
              <div className="flex-grow flex-1">
                {children}
              </div>
            </Providers>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
